import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

function getEnv(key: string) {
  return process.env[`MOD_${key}`] ?? process.env[`MODTOOLS_${key}`]
}

const MOD_EXPERIMENTAL = truthy("MOD_EXPERIMENTAL") || truthy("MODTOOLS_EXPERIMENTAL")
const MOD_DISABLE_CLAUDE_CODE = truthy("MOD_DISABLE_CLAUDE_CODE") || truthy("MODTOOLS_DISABLE_CLAUDE_CODE")
const MOD_DISABLE_CLAUDE_CODE_SKILLS =
  MOD_DISABLE_CLAUDE_CODE || truthy("MOD_DISABLE_CLAUDE_CODE_SKILLS") || truthy("MODTOOLS_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["MOD_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"] ?? process.env["MODTOOLS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: getEnv("OTEL_EXPORTER_OTLP_ENDPOINT"),
  OTEL_EXPORTER_OTLP_HEADERS: getEnv("OTEL_EXPORTER_OTLP_HEADERS"),

  MODTOOLS_AUTO_SHARE: truthy("MOD_AUTO_SHARE") || truthy("MODTOOLS_AUTO_SHARE"),
  MODTOOLS_AUTO_HEAP_SNAPSHOT: truthy("MOD_AUTO_HEAP_SNAPSHOT") || truthy("MODTOOLS_AUTO_HEAP_SNAPSHOT"),
  MODTOOLS_GIT_BASH_PATH: getEnv("GIT_BASH_PATH"),
  MODTOOLS_CONFIG: getEnv("CONFIG"),
  MODTOOLS_CONFIG_CONTENT: getEnv("CONFIG_CONTENT"),
  MODTOOLS_DISABLE_AUTOUPDATE: truthy("MOD_DISABLE_AUTOUPDATE") || truthy("MODTOOLS_DISABLE_AUTOUPDATE"),
  MODTOOLS_ALWAYS_NOTIFY_UPDATE: truthy("MOD_ALWAYS_NOTIFY_UPDATE") || truthy("MODTOOLS_ALWAYS_NOTIFY_UPDATE"),
  MODTOOLS_DISABLE_PRUNE: truthy("MOD_DISABLE_PRUNE") || truthy("MODTOOLS_DISABLE_PRUNE"),
  MODTOOLS_DISABLE_TERMINAL_TITLE: truthy("MOD_DISABLE_TERMINAL_TITLE") || truthy("MODTOOLS_DISABLE_TERMINAL_TITLE"),
  MODTOOLS_SHOW_TTFD: truthy("MOD_SHOW_TTFD") || truthy("MODTOOLS_SHOW_TTFD"),
  MODTOOLS_PERMISSION: getEnv("PERMISSION"),
  MODTOOLS_DISABLE_DEFAULT_PLUGINS: truthy("MOD_DISABLE_DEFAULT_PLUGINS") || truthy("MODTOOLS_DISABLE_DEFAULT_PLUGINS"),
  MODTOOLS_DISABLE_LSP_DOWNLOAD: truthy("MOD_DISABLE_LSP_DOWNLOAD") || truthy("MODTOOLS_DISABLE_LSP_DOWNLOAD"),
  MODTOOLS_ENABLE_EXPERIMENTAL_MODELS:
    truthy("MOD_ENABLE_EXPERIMENTAL_MODELS") || truthy("MODTOOLS_ENABLE_EXPERIMENTAL_MODELS"),
  MODTOOLS_DISABLE_AUTOCOMPACT: truthy("MOD_DISABLE_AUTOCOMPACT") || truthy("MODTOOLS_DISABLE_AUTOCOMPACT"),
  MODTOOLS_DISABLE_MODELS_FETCH: truthy("MOD_DISABLE_MODELS_FETCH") || truthy("MODTOOLS_DISABLE_MODELS_FETCH"),
  MODTOOLS_DISABLE_MOUSE: truthy("MOD_DISABLE_MOUSE") || truthy("MODTOOLS_DISABLE_MOUSE"),
  MODTOOLS_DISABLE_CLAUDE_CODE: MOD_DISABLE_CLAUDE_CODE,
  MODTOOLS_DISABLE_CLAUDE_CODE_PROMPT:
    MOD_DISABLE_CLAUDE_CODE || truthy("MOD_DISABLE_CLAUDE_CODE_PROMPT") || truthy("MODTOOLS_DISABLE_CLAUDE_CODE_PROMPT"),
  MODTOOLS_DISABLE_CLAUDE_CODE_SKILLS: MOD_DISABLE_CLAUDE_CODE_SKILLS,
  MODTOOLS_DISABLE_EXTERNAL_SKILLS:
    MOD_DISABLE_CLAUDE_CODE_SKILLS || truthy("MOD_DISABLE_EXTERNAL_SKILLS") || truthy("MODTOOLS_DISABLE_EXTERNAL_SKILLS"),
  MODTOOLS_FAKE_VCS: getEnv("FAKE_VCS"),
  MODTOOLS_SERVER_PASSWORD: getEnv("SERVER_PASSWORD"),
  MODTOOLS_SERVER_USERNAME: getEnv("SERVER_USERNAME"),
  MODTOOLS_ENABLE_QUESTION_TOOL: truthy("MOD_ENABLE_QUESTION_TOOL") || truthy("MODTOOLS_ENABLE_QUESTION_TOOL"),

  // Experimental
  MODTOOLS_EXPERIMENTAL: MOD_EXPERIMENTAL,
  MODTOOLS_EXPERIMENTAL_FILEWATCHER: Config.boolean("MOD_EXPERIMENTAL_FILEWATCHER")
    .pipe(Config.orElse(() => Config.boolean("MODTOOLS_EXPERIMENTAL_FILEWATCHER")))
    .pipe(Config.withDefault(false)),
  MODTOOLS_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("MOD_EXPERIMENTAL_DISABLE_FILEWATCHER")
    .pipe(Config.orElse(() => Config.boolean("MODTOOLS_EXPERIMENTAL_DISABLE_FILEWATCHER")))
    .pipe(Config.withDefault(false)),
  MODTOOLS_EXPERIMENTAL_ICON_DISCOVERY:
    MOD_EXPERIMENTAL || truthy("MOD_EXPERIMENTAL_ICON_DISCOVERY") || truthy("MODTOOLS_EXPERIMENTAL_ICON_DISCOVERY"),
  MODTOOLS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined
      ? process.platform === "win32"
      : truthy("MOD_EXPERIMENTAL_DISABLE_COPY_ON_SELECT") || truthy("MODTOOLS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  MODTOOLS_ENABLE_EXA:
    truthy("MOD_ENABLE_EXA") ||
    truthy("MODTOOLS_ENABLE_EXA") ||
    MOD_EXPERIMENTAL ||
    truthy("MOD_EXPERIMENTAL_EXA") ||
    truthy("MODTOOLS_EXPERIMENTAL_EXA"),
  MODTOOLS_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS:
    number("MOD_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS") ?? number("MODTOOLS_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  MODTOOLS_EXPERIMENTAL_OUTPUT_TOKEN_MAX:
    number("MOD_EXPERIMENTAL_OUTPUT_TOKEN_MAX") ?? number("MODTOOLS_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  MODTOOLS_EXPERIMENTAL_OXFMT:
    MOD_EXPERIMENTAL || truthy("MOD_EXPERIMENTAL_OXFMT") || truthy("MODTOOLS_EXPERIMENTAL_OXFMT"),
  MODTOOLS_EXPERIMENTAL_LSP_TY: truthy("MOD_EXPERIMENTAL_LSP_TY") || truthy("MODTOOLS_EXPERIMENTAL_LSP_TY"),
  MODTOOLS_EXPERIMENTAL_LSP_TOOL:
    MOD_EXPERIMENTAL || truthy("MOD_EXPERIMENTAL_LSP_TOOL") || truthy("MODTOOLS_EXPERIMENTAL_LSP_TOOL"),
  MODTOOLS_EXPERIMENTAL_PLAN_MODE:
    MOD_EXPERIMENTAL || truthy("MOD_EXPERIMENTAL_PLAN_MODE") || truthy("MODTOOLS_EXPERIMENTAL_PLAN_MODE"),
  MODTOOLS_EXPERIMENTAL_MARKDOWN: !falsy("MOD_EXPERIMENTAL_MARKDOWN") && !falsy("MODTOOLS_EXPERIMENTAL_MARKDOWN"),
  MODTOOLS_MODELS_URL: getEnv("MODELS_URL"),
  MODTOOLS_MODELS_PATH: getEnv("MODELS_PATH"),
  MODTOOLS_DISABLE_EMBEDDED_WEB_UI: truthy("MOD_DISABLE_EMBEDDED_WEB_UI") || truthy("MODTOOLS_DISABLE_EMBEDDED_WEB_UI"),
  MODTOOLS_DB: getEnv("DB"),
  MODTOOLS_DISABLE_CHANNEL_DB: truthy("MOD_DISABLE_CHANNEL_DB") || truthy("MODTOOLS_DISABLE_CHANNEL_DB"),
  MODTOOLS_SKIP_MIGRATIONS: truthy("MOD_SKIP_MIGRATIONS") || truthy("MODTOOLS_SKIP_MIGRATIONS"),
  MODTOOLS_STRICT_CONFIG_DEPS: truthy("MOD_STRICT_CONFIG_DEPS") || truthy("MODTOOLS_STRICT_CONFIG_DEPS"),

  MODTOOLS_WORKSPACE_ID: getEnv("WORKSPACE_ID"),
  MODTOOLS_EXPERIMENTAL_HTTPAPI: truthy("MOD_EXPERIMENTAL_HTTPAPI") || truthy("MODTOOLS_EXPERIMENTAL_HTTPAPI"),
  MODTOOLS_EXPERIMENTAL_WORKSPACES:
    MOD_EXPERIMENTAL || truthy("MOD_EXPERIMENTAL_WORKSPACES") || truthy("MODTOOLS_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get MODTOOLS_DISABLE_PROJECT_CONFIG() {
    return truthy("MOD_DISABLE_PROJECT_CONFIG") || truthy("MODTOOLS_DISABLE_PROJECT_CONFIG")
  },
  get MODTOOLS_TUI_CONFIG() {
    return getEnv("TUI_CONFIG")
  },
  get MODTOOLS_CONFIG_DIR() {
    return getEnv("CONFIG_DIR")
  },
  get MODTOOLS_PURE() {
    return truthy("MOD_PURE") || truthy("MODTOOLS_PURE")
  },
  get MODTOOLS_PLUGIN_META_FILE() {
    return getEnv("PLUGIN_META_FILE")
  },
  get MODTOOLS_CLIENT() {
    return getEnv("CLIENT") ?? "cli"
  },
}
