import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const MODTOOLS_EXPERIMENTAL = truthy("MODTOOLS_EXPERIMENTAL")
const MODTOOLS_DISABLE_CLAUDE_CODE = truthy("MODTOOLS_DISABLE_CLAUDE_CODE")
const MODTOOLS_DISABLE_CLAUDE_CODE_SKILLS =
  MODTOOLS_DISABLE_CLAUDE_CODE || truthy("MODTOOLS_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["MODTOOLS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  MODTOOLS_AUTO_SHARE: truthy("MODTOOLS_AUTO_SHARE"),
  MODTOOLS_AUTO_HEAP_SNAPSHOT: truthy("MODTOOLS_AUTO_HEAP_SNAPSHOT"),
  MODTOOLS_GIT_BASH_PATH: process.env["MODTOOLS_GIT_BASH_PATH"],
  MODTOOLS_CONFIG: process.env["MODTOOLS_CONFIG"],
  MODTOOLS_CONFIG_CONTENT: process.env["MODTOOLS_CONFIG_CONTENT"],
  MODTOOLS_DISABLE_AUTOUPDATE: truthy("MODTOOLS_DISABLE_AUTOUPDATE"),
  MODTOOLS_ALWAYS_NOTIFY_UPDATE: truthy("MODTOOLS_ALWAYS_NOTIFY_UPDATE"),
  MODTOOLS_DISABLE_PRUNE: truthy("MODTOOLS_DISABLE_PRUNE"),
  MODTOOLS_DISABLE_TERMINAL_TITLE: truthy("MODTOOLS_DISABLE_TERMINAL_TITLE"),
  MODTOOLS_SHOW_TTFD: truthy("MODTOOLS_SHOW_TTFD"),
  MODTOOLS_PERMISSION: process.env["MODTOOLS_PERMISSION"],
  MODTOOLS_DISABLE_DEFAULT_PLUGINS: truthy("MODTOOLS_DISABLE_DEFAULT_PLUGINS"),
  MODTOOLS_DISABLE_LSP_DOWNLOAD: truthy("MODTOOLS_DISABLE_LSP_DOWNLOAD"),
  MODTOOLS_ENABLE_EXPERIMENTAL_MODELS: truthy("MODTOOLS_ENABLE_EXPERIMENTAL_MODELS"),
  MODTOOLS_DISABLE_AUTOCOMPACT: truthy("MODTOOLS_DISABLE_AUTOCOMPACT"),
  MODTOOLS_DISABLE_MODELS_FETCH: truthy("MODTOOLS_DISABLE_MODELS_FETCH"),
  MODTOOLS_DISABLE_MOUSE: truthy("MODTOOLS_DISABLE_MOUSE"),
  MODTOOLS_DISABLE_CLAUDE_CODE,
  MODTOOLS_DISABLE_CLAUDE_CODE_PROMPT: MODTOOLS_DISABLE_CLAUDE_CODE || truthy("MODTOOLS_DISABLE_CLAUDE_CODE_PROMPT"),
  MODTOOLS_DISABLE_CLAUDE_CODE_SKILLS,
  MODTOOLS_DISABLE_EXTERNAL_SKILLS: MODTOOLS_DISABLE_CLAUDE_CODE_SKILLS || truthy("MODTOOLS_DISABLE_EXTERNAL_SKILLS"),
  MODTOOLS_FAKE_VCS: process.env["MODTOOLS_FAKE_VCS"],
  MODTOOLS_SERVER_PASSWORD: process.env["MODTOOLS_SERVER_PASSWORD"],
  MODTOOLS_SERVER_USERNAME: process.env["MODTOOLS_SERVER_USERNAME"],
  MODTOOLS_ENABLE_QUESTION_TOOL: truthy("MODTOOLS_ENABLE_QUESTION_TOOL"),

  // Experimental
  MODTOOLS_EXPERIMENTAL,
  MODTOOLS_EXPERIMENTAL_FILEWATCHER: Config.boolean("MODTOOLS_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  MODTOOLS_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("MODTOOLS_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  MODTOOLS_EXPERIMENTAL_ICON_DISCOVERY: MODTOOLS_EXPERIMENTAL || truthy("MODTOOLS_EXPERIMENTAL_ICON_DISCOVERY"),
  MODTOOLS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("MODTOOLS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  MODTOOLS_ENABLE_EXA: truthy("MODTOOLS_ENABLE_EXA") || MODTOOLS_EXPERIMENTAL || truthy("MODTOOLS_EXPERIMENTAL_EXA"),
  MODTOOLS_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("MODTOOLS_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  MODTOOLS_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("MODTOOLS_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  MODTOOLS_EXPERIMENTAL_OXFMT: MODTOOLS_EXPERIMENTAL || truthy("MODTOOLS_EXPERIMENTAL_OXFMT"),
  MODTOOLS_EXPERIMENTAL_LSP_TY: truthy("MODTOOLS_EXPERIMENTAL_LSP_TY"),
  MODTOOLS_EXPERIMENTAL_LSP_TOOL: MODTOOLS_EXPERIMENTAL || truthy("MODTOOLS_EXPERIMENTAL_LSP_TOOL"),
  MODTOOLS_EXPERIMENTAL_PLAN_MODE: MODTOOLS_EXPERIMENTAL || truthy("MODTOOLS_EXPERIMENTAL_PLAN_MODE"),
  MODTOOLS_EXPERIMENTAL_MARKDOWN: !falsy("MODTOOLS_EXPERIMENTAL_MARKDOWN"),
  MODTOOLS_MODELS_URL: process.env["MODTOOLS_MODELS_URL"],
  MODTOOLS_MODELS_PATH: process.env["MODTOOLS_MODELS_PATH"],
  MODTOOLS_DISABLE_EMBEDDED_WEB_UI: truthy("MODTOOLS_DISABLE_EMBEDDED_WEB_UI"),
  MODTOOLS_DB: process.env["MODTOOLS_DB"],
  MODTOOLS_DISABLE_CHANNEL_DB: truthy("MODTOOLS_DISABLE_CHANNEL_DB"),
  MODTOOLS_SKIP_MIGRATIONS: truthy("MODTOOLS_SKIP_MIGRATIONS"),
  MODTOOLS_STRICT_CONFIG_DEPS: truthy("MODTOOLS_STRICT_CONFIG_DEPS"),

  MODTOOLS_WORKSPACE_ID: process.env["MODTOOLS_WORKSPACE_ID"],
  MODTOOLS_EXPERIMENTAL_HTTPAPI: truthy("MODTOOLS_EXPERIMENTAL_HTTPAPI"),
  MODTOOLS_EXPERIMENTAL_WORKSPACES: MODTOOLS_EXPERIMENTAL || truthy("MODTOOLS_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get MODTOOLS_DISABLE_PROJECT_CONFIG() {
    return truthy("MODTOOLS_DISABLE_PROJECT_CONFIG")
  },
  get MODTOOLS_TUI_CONFIG() {
    return process.env["MODTOOLS_TUI_CONFIG"]
  },
  get MODTOOLS_CONFIG_DIR() {
    return process.env["MODTOOLS_CONFIG_DIR"]
  },
  get MODTOOLS_PURE() {
    return truthy("MODTOOLS_PURE")
  },
  get MODTOOLS_PLUGIN_META_FILE() {
    return process.env["MODTOOLS_PLUGIN_META_FILE"]
  },
  get MODTOOLS_CLIENT() {
    return process.env["MODTOOLS_CLIENT"] ?? "cli"
  },
}
