id = "mod"
name = "MOD"
description = "The open source coding agent from ECS."
version = "1.14.18"
schema_version = 1
authors = ["Embedded Computing Systems"]
repository = "https://github.com/Embedded-Computing-Systems/modtools"

[agent_servers.mod]
name = "MOD"
icon = "./icons/mod.svg"

[agent_servers.mod.targets.darwin-aarch64]
archive = "https://github.com/Embedded-Computing-Systems/modtools/releases/download/v1.14.18/mod-darwin-arm64.zip"
cmd = "./mod"
args = ["acp"]

[agent_servers.mod.targets.darwin-x86_64]
archive = "https://github.com/Embedded-Computing-Systems/modtools/releases/download/v1.14.18/mod-darwin-x64.zip"
cmd = "./mod"
args = ["acp"]

[agent_servers.mod.targets.linux-aarch64]
archive = "https://github.com/Embedded-Computing-Systems/modtools/releases/download/v1.14.18/mod-linux-arm64.tar.gz"
cmd = "./mod"
args = ["acp"]

[agent_servers.mod.targets.linux-x86_64]
archive = "https://github.com/Embedded-Computing-Systems/modtools/releases/download/v1.14.18/mod-linux-x64.tar.gz"
cmd = "./mod"
args = ["acp"]

[agent_servers.mod.targets.windows-x86_64]
archive = "https://github.com/Embedded-Computing-Systems/modtools/releases/download/v1.14.18/mod-windows-x64.zip"
cmd = "./mod.exe"
args = ["acp"]
