id = "modtools"
name = "Model-of-Design Tools"
description = "The open source coding agent."
version = "1.3.13"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/Embedded-Computing-Systems/modtools"

[agent_servers.modtools]
name = "Model-of-Design Tools"
icon = "./icons/modtools.svg"

[agent_servers.modtools.targets.darwin-aarch64]
archive = "https://github.com/Embedded-Computing-Systems/modtools/releases/download/v1.3.13/modtools-darwin-arm64.zip"
cmd = "./modtools"
args = ["acp"]

[agent_servers.modtools.targets.darwin-x86_64]
archive = "https://github.com/Embedded-Computing-Systems/modtools/releases/download/v1.3.13/modtools-darwin-x64.zip"
cmd = "./modtools"
args = ["acp"]

[agent_servers.modtools.targets.linux-aarch64]
archive = "https://github.com/Embedded-Computing-Systems/modtools/releases/download/v1.3.13/modtools-linux-arm64.tar.gz"
cmd = "./modtools"
args = ["acp"]

[agent_servers.modtools.targets.linux-x86_64]
archive = "https://github.com/Embedded-Computing-Systems/modtools/releases/download/v1.3.13/modtools-linux-x64.tar.gz"
cmd = "./modtools"
args = ["acp"]

[agent_servers.modtools.targets.windows-x86_64]
archive = "https://github.com/Embedded-Computing-Systems/modtools/releases/download/v1.3.13/modtools-windows-x64.zip"
cmd = "./modtools.exe"
args = ["acp"]
